branches:
  only:
  - master
  - development

language: swift

os: osx
osx_image: xcode10.1

cache:
  - cocoapods

#before_install:
#    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
#    - brew update
#    - pod --version
#    - pod update

before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true #need to clean up project at some stage using swiftlint 
  - pod repo update
  - pod update

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

script:
  - set -e
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list
  - xcodebuild clean build-for-testing test -workspace aqoo.xcworkspace -scheme aqoo -destination "platform=iOS Simulator,name=iPhone 6s,OS=11.3" -sdk iphonesimulator -toolchain XCode10.1 -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NOcd | xcpretty || true;
  #- xcodebuild clean build-for-testing -workspace aqoo.xcworkspace -scheme aqoo -destination "platform=iOS Simulator,name=iPhone 6s,OS=11.3" -sdk iphonesimulator -toolchain XCode10.1 -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NOcd | xcpretty || true;
