branches:
  only:
  - master
  - development
  - experimental

language: swift

os: osx
osx_image: xcode10.1

cache:
  - cocoapods

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty -N
  - brew update >/dev/null 2>&1
  - pod cache clean --all
  - rm -rf ./Pods/*
  - pod update


env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

script:
  - |
    cat > ./aqoo/Keys.plist <<- "EOF"
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>spfClientCallbackURL</key>
        <string>aqoo://</string>
        <key>spfClientSecret</key>
        <string>00000000000000000000000000000000</string>
        <key>spfClientId</key>
        <string>00000000000000000000000000000000</string>
      </dict>
    </plist>
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list
  - xcodebuild clean build-for-testing test -workspace aqoo.xcworkspace -scheme aqooCI -destination "platform=iOS Simulator,name=iPhone 6s,OS=11.4" -sdk iphonesimulator -toolchain XCode10.1 -configuration Debug -UseNewBuildSystem=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES | xcpretty || true
